### ISSUE TITLE
Doesn't support Scalars with length validation

### ISSUE THREAD

**Issue by dselman** [accordproject/vscode-web-extension#14]
# Bug Report 🐛

<img width="757" alt="image" src="https://github.com/accordproject/vscode-web-extension/assets/623108/9ee08775-9a0d-4e9d-9645-39e34498a6e1">

## Possible Solution

Update to latest CTO parser.

## Steps to Reproduce

1.
2.
3.
4.

### Desktop
 - OS: [e.g. macOS]
 - Browser: [e.g. Chrome, Safari]
 - Version: [e.g. 0.22.15]

**Comment by mttrbrts** [comment]
@anablaz thank you for your investigation and comment. I'll close the issue 🙏
